<a href="https://colab.research.google.com/github/Haricharanpampad/machine-learning/blob/main/Model_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [4]:
heart_data=pd.read_csv('/content/heart.csv')

In [6]:
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [8]:
X=heart_data.drop(columns='target',axis=1)
Y=heart_data['target']

In [9]:
X=np.asarray(X)
Y=np.asarray(Y)

#Model selection
comparing models with default hyper parameters using cross validation

In [10]:
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [13]:
def compare_models_cross_validation():
  for model in models:
    cv_score=cross_val_score(model,X,Y,cv=5)
    mean_accuracy=sum(cv_score)/len(cv_score)
    mean_accuracy=mean_accuracy*100
    mean_accuracy=round(mean_accuracy,2)
    print('cross val accuracies for model',model,'=',cv_score)
    print('accuracy score of ',model,'=',mean_accuracy,'%')
    print('------------------------------------')

In [14]:
compare_models_cross_validation()

cross val accuracies for model LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
accuracy score of  LogisticRegression(max_iter=1000) = 82.83 %
------------------------------------
cross val accuracies for model SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
accuracy score of  SVC(kernel='linear') = 82.83 %
------------------------------------
cross val accuracies for model KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
accuracy score of  KNeighborsClassifier() = 64.39 %
------------------------------------
cross val accuracies for model RandomForestClassifier(random_state=0) = [0.85245902 0.90163934 0.81967213 0.81666667 0.8       ]
accuracy score of  RandomForestClassifier(random_state=0) = 83.81 %
------------------------------------

Raandom forest  classifier as highest accuracy

comparing models with  hyper tuned  parameters using cross validation
technique(Grid search CV)

In [15]:
model_list=[LogisticRegression(max_iter=10000),SVC(),KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [17]:
#dictionary of hyperparameters
model_hyperparameters={
    'log_reg_hyperparameters':{
        'C':[1,5,10,20]
    },
    'svc_hyperparameters':{
        'kernel':['linear','poly','rbf','sigmoid'],
        'C':[1,5,10,20]
    },
    'KNN_hyperparameters':{
        'n_neighbors':[3,5,10]
    },
    'random_forest_hyperparameters':{
        'n_estimators':[10,20,50,100]
    }
}

In [18]:
type(model_hyperparameters)

dict

In [19]:
model_keys=list(model_hyperparameters.keys())
print(model_keys)

['log_reg_hyperparameters', 'svc_hyperparameters', 'KNN_hyperparameters', 'random_forest_hyperparameters']

Applying GridSearchCV

In [30]:
def ModelSelection(list_of_models,hyperparameters_dic):
  result=[]
  i=0
  for model in list_of_models:
    key=model_keys[i]
    params=hyperparameters_dic[key]
    i+=1
    print(model)
    print(params)
    print('--------------------------------------------------')

    classifier=GridSearchCV(model,params,cv=5)
    classifier.fit(X,Y)

    result.append({
        'model used':model,
        'highest score':classifier.best_score_,
        'best hyperparams':classifier.best_params_
    })
  result_dataframe=pd.DataFrame(result,columns=['model used','highest score','best hyperparams'])
  return result_dataframe

In [31]:
ModelSelection(model_list,model_hyperparameters)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}
--------------------------------------------------
SVC()
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
--------------------------------------------------
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
--------------------------------------------------
RandomForestClassifier(random_state=0)
{'n_estimators': [10, 20, 50, 100]}
--------------------------------------------------

                               model used  ...              best hyperparams
0      LogisticRegression(max_iter=10000)  ...                      {'C': 5}
1                                   SVC()  ...  {'C': 1, 'kernel': 'linear'}
2                  KNeighborsClassifier()  ...            {'n_neighbors': 5}
3  RandomForestClassifier(random_state=0)  ...         {'n_estimators': 100}

[4 rows x 3 columns]